esphome:
  name: your-name
  friendly_name: yourbest-name

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "APIKEYHOMEASSISTANT"

ota:
  platform: esphome


wifi:
  ssid: !secret wifi_ssid #secret doc
  password: !secret wifi_password #secret doc

  manual_ip:
    static_ip: your static ip
    gateway: your gateway
    subnet: your subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "capteur--chambre"
    password: "generatepassw"

captive_portal:
    

sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Température"
    humidity:
      name: "Humidité"
    update_interval: 900s #custom this for refresh sensor interval
    model: DHT22

switch:
  # Restart button
  - platform: restart
    name: "Redémarrage"